version: "3"
services:
  phpcl-jumpstart-drupal:
    container_name: phpcl_jumpstart_drupal
    hostname: jumpstart-drupal
    image: asclinux/linuxforphp-8.2-ultimate:7.4-nts
    volumes:
     - ".:/srv/jumpstart"
     - "./docker/httpd-vhosts.conf:/etc/httpd/extra/httpd-vhosts.conf"
    ports:
     - "8283:80"
     - "10443:443"
     - "2222:22"
    build: ./docker
    restart: always
    command: lfphp --phpfpm --apache </dev/null >/dev/null 2&>1 &
    networks:
      app_net:
        ipv4_address: 172.16.2.99
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.2.0/24"
